plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'coverage/**/*'
    - 'node_modules/**/*'
    - 'Gemfile.lock'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'app/models/file_node.rb'
    - 'app/services/file_creation_service.rb'

Metrics/ClassLength:
  Max: 160

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'app/models/file_content.rb'
    - 'app/models/file_node.rb'
    - 'app/services/file_creation_service.rb'

Metrics/PerceivedComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'app/models/file_content.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Rails/DynamicFindBy:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma 